const express = require('express');
const router = express.Router();
const multer = require('multer');
const TweetController = require('../controller/tweetController.ts');
const storage = multer.memoryStorage();
const checkAuth = require('../middlewares/checkAuth');
const upload = multer({ storage: storage });
router.post('/create', upload.single('image'),checkAuth,TweetController.createTweet);
router.patch('/update/:tweetId', TweetController.updateTweet);
router.post('/like/:tweetId', TweetController.likeTweet);
router.post('/unlike/:tweetId', TweetController.unlikeTweet);
router.post("/comment/:tweetId", TweetController.commentTweet);
router.post("/delete/:tweetId", TweetController.deleteTweet);
router.get("/getFollowersTweets", checkAuth,TweetController.getFollowersTweets);
module.exports = router;