const express = require('express');
const router = express.Router();
const multer = require('multer');
const TweetController = require('../controller/tweetController.ts');
const storage = multer.memoryStorage();
const checkAuth = require('../middlewares/checkAuth');
const upload = multer({ storage: storage });
router.post('/create', upload.single('image'),checkAuth,TweetController.createTweet);
router.patch('/update/:tweetId',checkAuth, TweetController.updateTweet);
router.post('/like/:tweetId', checkAuth,TweetController.likeTweet);
router.post('/unlike/:tweetId', checkAuth,TweetController.unlikeTweet);
router.post("/comment/:tweetId", TweetController.commentTweet);
router.delete("/delete/:tweetId", checkAuth,TweetController.deleteTweet);
router.get("/getFollowersTweets", checkAuth,TweetController.getFollowersTweets);
router.post("/bookmark/:tweetId", checkAuth,TweetController.bookmarkTweet);
router.post("/unbookmark/:tweetId", checkAuth,TweetController.unbookmarkTweet);
router.get("/getBookmarks", checkAuth,TweetController.getBookmarks);
router.get("/getTweets/:userId", TweetController.getTweets);
router.get("/getAllTweets",checkAuth, TweetController.getAllTweets);
module.exports = router;