const express=require('express');
const router=express.Router();
const multer=require('multer');
const UserController=require('../controller/userController.ts');
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });
const checkAuth=require('../middlewares/checkAuth');
router.post('/register',UserController.register);
router.post('/login',UserController.login);
router.post('/follow/:personId',checkAuth,UserController.follow);
router.post('/unfollow/:personId',checkAuth, UserController.unfollow);
router.post('/uploadProfilePicture',upload.single('image'),UserController.uploadProfilePicture);
router.get('/profile/:userId',UserController.getProfile);
router.get("/getFollowers/:userId",UserController.getFollowers);
router.get("/getFollowing/:userId",UserController.getFollowing);
router.get("/getOwnProfile",checkAuth,UserController.getOwnProfile);
router.post("/updateProfile",checkAuth,UserController.updateProfile);

router.post("/search",checkAuth,UserController.search);
module.exports=router;